name: PostgreSQL Service Example
on: push

jobs:
 
  runner-job:
   
    runs-on: ubuntu-latest

   
    services:
      
      postgres:
       
        image: postgres:14 
       
        env:
          POSTGRES_PASSWORD: 090cae6d0e6c21e338d8e83b2ac1a85db99ea24b0d3c8d96a009657cab77bb36
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          
          - 5432:5432

    steps:
     
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Connect to PostgreSQL
  
        #run: npm test
        
        run: node client.js
       
        env:
          
          POSTGRES_HOST: ec2-3-224-164-189.compute-1.amazonaws.com
         
          POSTGRES_PORT: 5432